### ISSUE TITLE
The generate joint are rotated

### ISSUE THREAD

**Issue by theoldgun** [papagina/Auto_Conditioned_RNN_motion#2]
Nice work!
I have a question~

The joint points in the data generated by training model are rotated. The joint of the original BVH data is not rotated, but when the original BVH data is converted to NPY and after the training is transferred out of the BVH, the joints begin to rotate. How to avoid this problem?
thank you！

**Comment by papagina** [comment]
This inverse kinematic code here doesn't consider the temporal rotation smoothness or the joint rotation constraint of the physical body. When we use the output bvh file to drive avatars in Maya, we simply set the animation frame rate to be the same frame rate as in the bvh file so that the motion looks right.  If you want to interpolate for higher frame rate, the interpolation will go wrong. So my recommendation is to seek for other more advanced inverse kinematic code if you have these requirements in your applications. Hope that I have answered your question.

**Comment by theoldgun** [comment]
Thank you! Very nice~
